### PR TITLE
Requirements

### PR DESCRIPTION
**Pull request by sanggookang**
Requirements added.

Todo:
- [x] Requirements for CPU installation
- [ ] Requirements for GPU installation

### CODE REVIEW

**Review by ClimbsRocks — COMMENTED** [review]
i've heard that it's generally best to pin minimum versions of dependencies, not necessarily exact versions. that way if you install multiple different projects, it's easier to resolve to one global set. 

i'd also recommend against requiring stuff for tests, or putting that into a separate dependency file like `requirements/testing.txt`

**Comment by ClimbsRocks** [comment]
also, i love that you've already set up required reviews :) i'll look into setting up travis-ci

**Comment by ClimbsRocks** [comment]
i also created an org for us here if we'd rather do this somewhere a bit more centrally: https://github.com/autodeepnet/autodeepnet

**Review by ClimbsRocks — APPROVED** [review]

**Comment by sanggookang** [comment]
got it. just changed all the requirements to be minimum requirements instead. Should we make a testing requirements too then with everything that would be needed for any testing in the future? I feel like it'd require much of the same packages as the normal requirements.

**Comment by ClimbsRocks** [comment]
@sanggookang it'd just be the incremental packages. at testing time, we'd install the normal requirements, and then also the testing requirements after.

**Pull request merged**
